apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: dv-local-observability-prometheus
data:
  CLUSTER_NAME: Local
  ENVIRONMENT: dv
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"